### PR TITLE
Remove prefetcher code

### PR DESCRIPTION
**Pull request by rdpsin**
This commit removes the current prefetcher code.

Signed-off-by: Rishabh Singhvi <rdpsin@amazon.com>

*Issue #, if available:*

*Description of changes:*

*Testing performed:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by vkuzniet — APPROVED** [review]
LGTM. I'm fine with removing BackgroundTaskManager in the next PR.

**Comment by rdpsin** [comment]
Removed background task manager code in this PR.

**Review by vkuzniet — APPROVED** [review]

**Review by kzys — COMMENTED** [review]
Looks good to me. Can you rebase the PR? It might clear the integration test failure.

**Review by hanyuel — APPROVED** [review]

**Review by vkuzniet — APPROVED** [review]

**Comment by sbuckfelder** [comment]
While this all looks fine - what testing did you do that gives you confidence that this will work?

**Comment by rdpsin** [comment]
Not sure if testing is required. This PR is only for removing code that we don't want. It's the same as setting `no_background_fetch = true`.

**Review by Kern-- — APPROVED** [review]

**Pull request merged**
