### PR TITLE
Update README.md to make evaluation easier for newcomers

### PR DESCRIPTION
**Pull request by inf3rnus**
Hey all,

Not saying this is the best copy, but the first thing I wanted to do with this was evaluate for myself it makes sense to use for my use case. i.e. I needed to evaluate performance, specifically if it's faster to use this then to just docker pull.

There's a useful command for deleting layers in Debug... Doesn't mentally map as "debug" for me, so by just adding some extra context to the link, I think that will lead to a less frictional experience for other users.

Regards,

Aaron

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sondavidb** [comment]
Hi, thanks for the contribution!

Seems like a fine change to me, but just need to handle a couple of due process items:

1. We require all commits to the repository to be signed with DCO (i.e. `Signed-off-by: Foo Bar <foo@bar.com>` at the end of the commit message)
2. For licensing reasons, we require PRs to append the following line to the bottom: `By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.`

Once that gets updated I'll run workflows and approve if it looks good. Thanks!

**Comment by inf3rnus** [comment]
Alrighty changes made!

Please lmk if there's anything else I need to do.

**Comment by sondavidb** [comment]
Ah, we do also need the DCO signing to be signed with your legal name, not a pseudonym. Forgot to mention that before, sorry

**Comment by inf3rnus** [comment]
Np np. Alrighty, updated, everything good on my end? 

Also fyi, noticed one of the workflows is now failing, and I believe it's due to the `.github/new-pull-request-labels.yml` file not being formatted correctly. 

Looks like it was changed on commit `184d564b9003d0fca62b6e8cc331bb5451a06bc3`

**Review by sondavidb — APPROVED** [review]
Looks great, thanks!

> noticed one of the workflows is now failing

Looks like it's a bug on our end, we'll fix it up before merging.

**Comment by austinvazquez** [comment]
Hey folks, I looked into the failing workflow here and opened #1277 to resolve. There issue with the configuration format for the new pull request labeler workflow.

**Comment by austinvazquez** [comment]
@inf3rnus, the fix has been merged. Can you rebase your branch and push?

**Comment by inf3rnus** [comment]
@austinvazquez Okie dokie, everything should be g2g

**Review by Kern-- — APPROVED** [review]

**Comment by sondavidb** [comment]
Thanks again!

**Pull request merged**
