### PR TITLE
Pin GitHub Actions packages using commit SHA

### PR DESCRIPTION
**Pull request by austinvazquez**
**Issue #, if available:**
N/A

**Description of changes:**
This pull request pins third-party GitHub Actions packages by commit SHA based on recommended best practices in [Security Hardening for GitHub Actions](https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions).

Note [dependabot](https://github.com/dependabot/dependabot-core/issues/4691) will keep the human readable version tag up-to-date.

**Testing performed:**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by Kern--** [comment]
Is dependabot going to automatically update these anyway? Do we really gain anything with this?

**Comment by austinvazquez** [comment]
> Is dependabot going to automatically update these anyway? Do we really gain anything with this?

Dependabot will keep these packages updated, but the approve and merge step is still manual. The benefit is partially build reproducibility but there also is a security aspect.

**Comment by sondavidb** [comment]
This practice seems to only apply for third-party actions based on the link you provided. I think we should keep most of the actions as is and only pin the non-GH Actions ones (aka create-pull-request and action-gh-release) to a specific commit.

**Comment by austinvazquez** [comment]
Going to close this one for now and we can revisit it if needed. The original intent was to pin CI dependencies to for security concerns but the likelihood of backdoors being introduced into actions packages might not be likely.

**Pull request closed without merging**
