### PR TITLE
Replace "soci image rpull" with common base command

### PR DESCRIPTION
**Pull request by sondavidb**
**Issue #, if available:**

**Description of changes:**
Similar to #912's change making "nerdctl run" consolidated into one common command, this has the same function.

**Testing performed:**
go fmt passed. Should be no functional changes so as long as the replacement was done properly it should be alright.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sondavidb** [comment]
That's awkward...turns out flags don't pass down the hierarchy in our CLI (which is strange, because [it seems they're supported](https://github.com/urfave/cli/issues/142)).

**Comment by Kern--** [comment]
Oh, right. This is a slightly different issue than that upstream issue. urfave flags are tightly scoped to the command hierarchy.
```
soci --content-store soci image rpull
```
is not the same as

```
soci image rpull --content-store soci
```

The former is expecting the flag to be defined on the root command while the latter is expecting the flag to be defined on the `rpull` command.

**Comment by sondavidb** [comment]
Ah, I see. But I would assume that kind of behavior is supported? I recall someone mentioning that it is supported in v3, so maybe we can hold off on this until then (unless this is already supported).

**Comment by sondavidb** [comment]
Closing this for now since this can't work with current version of urfave/cli CLI.

**Pull request closed without merging**
