### PR TITLE
Eliminate containerd / runc / soci compiles from integration tests

### LINKED ISSUE #267: [BUG] Integration tests rebuild soci when non-test code hasn't changed
**Describe the bug**
`make integration` runs the `pre-build` make target which deletes any existing compiled binary, then creating the docker image to run soci during the tests requires recompiling soci.

**Steps To Reproduce**
1. `make`
2. `make integration`

**Expected behavior**
`out/soci` is not deleted if none of the non-test code has changed (e.g. when implementing a new test) and the existing binary is used to run the test(s).

### LINKED ISSUE #268: [BUG] Dockerfile builds containerd from source unnecessarily
**Describe the bug**
`docker build .` and `make integration` both download and compile the containerd source as part of creating the soci image, which significantly increases testing time.

**Steps To Reproduce**
`make integration`

**Expected behavior**
Download containerd from a release, like we already do for nerdctl

### LINKED ISSUE #269: [BUG] Dockerfile builds runc from source unnecessarily
**Describe the bug**
`docker build .` and `make integration` both download and compile the runc source as part of creating the soci image, which significantly increases testing time.

**Steps To Reproduce**
`make integration`

**Expected behavior**
Download runc from a release, like we already do for nerdctl

### PR DESCRIPTION
**Pull request by sparr**
*Issue #, if available:*
Closes #267
Closes #268
Closes #269

*Description of changes:*
Download containerd and runc from releases instead of compiling during integration test runs.
Run `build` make target outside the integration test container and include `out/` in dockerfile context so that soci won't be re-built when it isn't necessary.

*Testing performed:*
Ran integration test suite and benchmarked a single non-trivial test.
With this PR, the RpullImageWithMinLayerSize test run individually takes ~31 seconds on my dev desktop. Without, ~160 seconds.

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by Kern-- — APPROVED** [review]

**Comment by rdpsin** [comment]
Why are there no checks?

**Comment by sparr** [comment]
@rdpsin What sort of checks are you referring to?

**Comment by hanyuel** [comment]
> @rdpsin What sort of checks are you referring to?

@sparr The Github actions for tests didn't kick off.

**Comment by sparr** [comment]
Oh. I don't know. They fired previously and complained about lack of DCO on my commit, then I added it and pushed and they didn't fire again. I'll try a noop push to trigger them again.

**Review by turan18 — APPROVED** [review]

**Review by Kern-- — APPROVED** [review]

**Pull request merged**
