### PR TITLE
Run "make benchmarks" on GitHub Actions

### PR DESCRIPTION
**Pull request by kzys**
While we might not be able to trust the numbers, this will help us to make sure that the target doesn't have any build errors.

Signed-off-by: Kazuyoshi Kato <katokazu@amazon.com>

*Issue #, if available:*

*Description of changes:*

*Testing performed:*

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by kzys** [comment]
We actually have build errors right now.

@sbuckfelder or @hanyuel - Would it be fixed by one of your PRs?

**Comment by kzys** [comment]
> Also, I think to do this we need to investigate if we can use a public repo (I think Docker might support referrers now?)

It will be, according to https://www.docker.com/blog/announcing-docker-hub-oci-artifacts-support/

> But, our mission doesn’t end here! We’re continually working to bolster our OCI support. While the OCI Artifact Specification [is considered a release candidate](https://github.com/opencontainers/image-spec/commit/19a74bcb54ba211005a68d85c6b359c2947721ce), full Docker Hub support for OCI Reference Types and the accompanying [Referrers API](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#api) is on the horizon. Stay tuned for upcoming enhancements, improved repo organization, and more.

We also could consider https://github.com/opencontainers/distribution-spec/blob/main/spec.md#backwards-compatibility. oras-go is supporting that apparently (see https://github.com/oras-project/oras-go/issues/354).

**Comment by sbuckfelder** [comment]
So just to confirm we are agreed that this PR is on hold until we can get images and soci artifacts in a public repo?

**Comment by vkuzniet** [comment]
#239

**Pull request closed without merging**
