### PR TITLE
Remove "image rpull" from CLI

### PR DESCRIPTION
**Pull request by sondavidb**
As an effort to streamline our CLI usage, `image rpull` has been removed. While it technically retains some functionality special to SOCI, it is ultimately up to the CLI to pass the requisite parameters to the remote snapshotter.

This also removes the last of our references to `ctr`.

**Issue #, if available:**
#677
#841 

**Description of changes:**

Removed `cmd/soci/commands/image/`, consequentially also removing the `rpull` command. Replaced all instances of `soci image rpull` with `nerdctl pull --snapshotter soci` in the testing suite.

**Testing performed:**
`make integration`

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by sondavidb** [comment]
Our docs should probably be updated to reflect this.

Would this be considered a breaking change? I wonder if we want to stall this for a later time. I don't really think so, but worth thinking about.

**Comment by austinvazquez** [comment]
> Our docs should probably be updated to reflect this.

Can we update docs with this PR so the change is atomic?

> Would this be considered a breaking change? I wonder if we want to stall this for a later time. I don't really think so, but worth thinking about.

Yes, but that also is the nature of projects <1.0.0. Typically there isn't much expectation for API stability until 1.0 is released.

**Comment by sondavidb** [comment]
Docs updated to reflect these changes.

Since we are now relegating implementation of remote snapshot pulling to other CLIs now, we should include an extra paragraph about how to connect it to our CLI. Once this is merged I can open an issue for this.

**Review by Kern-- — APPROVED** [review]

**Comment by turan18** [comment]
> Since we are now relegating implementation of remote snapshot pulling to other CLIs now, we should include an extra paragraph about how to connect it to our CLI. Once this is merged I can open an issue for this.

I think this can be a part of #677. We should make sure to mention these changes in our next release. The tracking issue #841 has the v0.5 milestone tag so that should be enforcing mechanism for us to not forget to do that.

**Review by turan18 — APPROVED** [review]

**Pull request merged**
