### PR TITLE
Update Go version in workflows

### PR DESCRIPTION
**Pull request by sondavidb**
**Issue #, if available:**

**Description of changes:**
Updated Go version from v1.20.12 -> v1.20.13 in workflows

**Testing performed:**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by turan18 — DISMISSED** [review]

**Review by austinvazquez — CHANGES_REQUESTED** [review]
You need to also update the Go version in the top level Dockerfile which will trigger the workflows to run.

**Comment by sondavidb** [comment]
Thanks for the catch @austinvazquez. Added a failsafe to the Dockerfile in case this happens again. This could also be useful if we ever want to start testing multiple go versions (e.g. 1.21).

**Comment by austinvazquez** [comment]
Closing and reopening to pick up workflow changes.

**Comment by sondavidb** [comment]
It looks like the new env section overwrites the old one, and I don't see a way to carry it over.

I think I'll just revert these changes for now. I think we'll want to do another matrix like we do with containerd anyway if we want to test multiple Go versions, and that would warrant a separate PR IMO.

**Review by austinvazquez — APPROVED** [review]

**Review by turan18 — APPROVED** [review]

**Pull request merged**
