### PR TITLE
Update containerd versions in workflows

### PR DESCRIPTION
**Pull request by sondavidb**
**Issue #, if available:**

**Description of changes:**
Updated containerd versions in matrix.
v1.6.19 -> v1.6.26
v1.7.0 -> v1.7.11

**Testing performed:**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by turan18 — DISMISSED** [review]

**Review by austinvazquez — CHANGES_REQUESTED** [review]
The changes themselves LGTM, but can you run the build workflow in your fork and paste the link under testing performed in the PR description just to validate the integration tests pass with the new containerd versions.

For context, our workflows do not currently run when modified. We have #911 to track that work.

**Comment by austinvazquez** [comment]
Opened #1028 to help with this.

**Comment by sondavidb** [comment]
Rebased after changes in #1028 so now it should auto-run the integration tests.

While we're here, I wanted a sanity check — our Dockerfile has an argument `CONTAINERD_VERSION` that gets overwritten in our GH Actions workflow. Is there any particular reason we keep this variable at 1.6.17? I wonder if we should change it to reflect the latest version(s?) in our workflow. It wouldn't affect us, but might help clear confusion for future users looking to run the testing suite locally.

**Comment by turan18** [comment]
> Rebased after changes in #1028 so now it should auto-run the integration tests.
> 
> While we're here, I wanted a sanity check — our Dockerfile has an argument `CONTAINERD_VERSION` that gets overwritten in our GH Actions workflow. Is there any particular reason we keep this variable at 1.6.17? I wonder if we should change it to reflect the latest version(s?) in our workflow. It wouldn't affect us, but might help clear confusion for future users looking to run the testing suite locally.

We pass the containerd version from GH actions as a build argument, 1.6.17 is just the default, meaning if don't explicitly set one it's used. I do think it's a good idea to update the Dockerfile whenever we make relevant changes to our GA actions, as it can cause a discrepancy between our GA tests and local tests.

**Comment by sondavidb** [comment]
Thanks. Change has been made to reflect @turan18's suggestion.

**Review by austinvazquez — APPROVED** [review]

**Review by turan18 — APPROVED** [review]

**Pull request merged**
