### PR TITLE
Add separate DCO workflow

### PR DESCRIPTION
**Pull request by coderbirju**
This commit adds a new workflow called 'prebuild' which contains the DCO and lint checks. The Dco check needs to run on every code change regardless of whether it is a documentation or code change hence seperating it out into a different workflow, this will run for all pull and merge requests

**Issue #, if available:**

**Description of changes:**

**Testing performed:**

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by turan18** [comment]
> Would removing the benchmark job from build.yml be a better split?

Yeah, I think the DCO change should be it's own PR and we can have the benchmarking automation change be separate from this.

**Comment by coderbirju** [comment]
> > Would removing the benchmark job from build.yml be a better split?
> 
> Yeah, I think the DCO change should be it's own PR and we can have the benchmarking automation change be separate from this.

Understood. Updated

**Comment by sparr** [comment]
The two PRs still have the same title and substantially similar descriptions, could you update them to describe the contents?

**Comment by coderbirju** [comment]
> The two PRs still have the same title and substantially similar descriptions, could you update them to describe the contents?

I have updated the title of the other PR to reflect the changes, also updated the description of this PR

**Review by turan18 — APPROVED** [review]

**Review by Kern-- — APPROVED** [review]

**Pull request merged**
